### ISSUE TITLE
Network aliases not shown

### ISSUE THREAD

**Issue by Neirda24** [LeoVerto/docker-network-graph#9]
you can write something like this in docker-compose:
```yaml
nginx:
    networks:
        webserver:
            aliases:
                - 'local.myapp'
```
It would be great to see the aliases per network (I currently have an issue using this and your tool might be very helpful !)
